export const actionTypes = {
    STUDENT_LIST : "STUDENT_LIST",
    REMOVE_STUDENT_LIST : "REMOVE_STUDENT_LIST",
    NEW_STUDENT : "NEW_STUDENT",
    CREATE_STUDENT : "CREATE_STUDENT",
    EDIT_STUDENT : "EDIT_STUDENT",
    VALUE_CHANGE : "VALUE_CHANGE",
    INITIAL_STATE : "INITIAL_STATE"
}